### PR TITLE
move array & object related tags to a separate file

### PR DESCRIPTION
**Pull request by Canehdian**
declutter the global docs by moving the tags for arrays & objects to a separate file for easier browsing

### CODE REVIEW

**Comment by DracoClaw** [comment]
please update sidebars.js to include your new page

additionally please change the file name to `arrays-and-objects`, the page title is whats seen and can still use the &

**Comment by Canehdian** [comment]
how do I make it appear as "Arrays & Objects" in the sidebar?

**Comment by DracoClaw** [comment]
from what i can see based on https://docs.atlas.bot/scripts/options-and-parameters, its done by the header (#Arrays & Objects)

**Comment by Canehdian** [comment]
I've already got that, it still appears as "arrays-&-objects"

**Comment by Grainus** [comment]
https://www.youtube.com/watch?v=sAXZbfLzJUg

**Comment by Grainus** [comment]
Additional info on the PR: Updates the docusaurus and node.js versions used, and changes the project version from 1.0.0 to 1.1.0

**Pull request merged**
